import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json([
    {
      id: 1,
      title: "To Kill a Mockingbird",
      author: "Harper Lee",
      year: 1960,
      genre: ["Fiction", "Classic"],
      rating: 4.8,
      pages: 281,
      language: "English",
    },
    {
      id: 2,
      title: "1984",
      author: "George Orwell",
      year: 1949,
      genre: ["Fiction", "Dystopian"],
      rating: 4.7,
      pages: 328,
      language: "English",
    },
    {
      id: 3,
      title: "Pride and Prejudice",
      author: "Jane Austen",
      year: 1813,
      genre: ["Fiction", "Romance"],
      rating: 4.6,
      pages: 279,
      language: "English",
    },
    {
      id: 4,
      title: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
      year: 1925,
      genre: ["Fiction", "Classic"],
      rating: 4.4,
      pages: 180,
      language: "English",
    },
    {
      id: 5,
      title: "Moby Dick",
      author: "Herman Melville",
      year: 1851,
      genre: ["Fiction", "Adventure"],
      rating: 4.1,
      pages: 635,
      language: "English",
    },
    {
      id: 6,
      title: "War and Peace",
      author: "Leo Tolstoy",
      year: 1869,
      genre: ["Fiction", "Historical"],
      rating: 4.5,
      pages: 1225,
      language: "Russian",
    },
    {
      id: 7,
      title: "The Catcher in the Rye",
      author: "J.D. Salinger",
      year: 1951,
      genre: ["Fiction", "Coming-of-Age"],
      rating: 4.2,
      pages: 214,
      language: "English",
    },
    {
      id: 8,
      title: "The Hobbit",
      author: "J.R.R. Tolkien",
      year: 1937,
      genre: ["Fantasy", "Adventure"],
      rating: 4.7,
      pages: 310,
      language: "English",
    },
    {
      id: 9,
      title: "Crime and Punishment",
      author: "Fyodor Dostoevsky",
      year: 1866,
      genre: ["Fiction", "Psychological"],
      rating: 4.6,
      pages: 671,
      language: "Russian",
    },
    {
      id: 10,
      title: "The Alchemist",
      author: "Paulo Coelho",
      year: 1988,
      genre: ["Fiction", "Philosophical"],
      rating: 4.3,
      pages: 197,
      language: "Portuguese",
    },
    {
      id: 11,
      title: "The Odyssey",
      author: "Homer",
      year: -700,
      genre: ["Epic", "Adventure"],
      rating: 4.4,
      pages: 541,
      language: "Greek",
    },
    {
      id: 12,
      title: "Brave New World",
      author: "Aldous Huxley",
      year: 1932,
      genre: ["Fiction", "Dystopian"],
      rating: 4.5,
      pages: 268,
      language: "English",
    },
    {
      id: 13,
      title: "The Lord of the Rings",
      author: "J.R.R. Tolkien",
      year: 1954,
      genre: ["Fantasy", "Adventure"],
      rating: 4.9,
      pages: 1178,
      language: "English",
    },
    {
      id: 14,
      title: "Anna Karenina",
      author: "Leo Tolstoy",
      year: 1877,
      genre: ["Fiction", "Romance"],
      rating: 4.5,
      pages: 864,
      language: "Russian",
    },
    {
      id: 15,
      title: "The Brothers Karamazov",
      author: "Fyodor Dostoevsky",
      year: 1880,
      genre: ["Fiction", "Philosophical"],
      rating: 4.7,
      pages: 824,
      language: "Russian",
    },
    {
      id: 16,
      title: "Harry Potter and the Philosopher's Stone",
      author: "J.K. Rowling",
      year: 1997,
      genre: ["Fantasy", "Adventure"],
      rating: 4.8,
      pages: 223,
      language: "English",
    },
    {
      id: 17,
      title: "Alice's Adventures in Wonderland",
      author: "Lewis Carroll",
      year: 1865,
      genre: ["Fantasy", "Adventure"],
      rating: 4.3,
      pages: 201,
      language: "English",
    },
    {
      id: 18,
      title: "Don Quixote",
      author: "Miguel de Cervantes",
      year: 1605,
      genre: ["Fiction", "Adventure"],
      rating: 4.2,
      pages: 863,
      language: "Spanish",
    },
    {
      id: 19,
      title: "Meditations",
      author: "Marcus Aurelius",
      year: 180,
      genre: ["Philosophy", "Non-Fiction"],
      rating: 4.6,
      pages: 254,
      language: "Greek",
    },
    {
      id: 20,
      title: "The Little Prince",
      author: "Antoine de Saint-Exupéry",
      year: 1943,
      genre: ["Fiction", "Children"],
      rating: 4.7,
      pages: 96,
      language: "French",
    },
  ]);
}

export async function POST(request: Request) {
  const body = await request.json();

  return NextResponse.json(
    {
      message: "User created",
    },
    {
      status: 201,
    },
  );
}
